-- insert into question(ques_num,ques_content)
--             values(1,'좋아하는 음식이 뭐야?');
-- insert into question(ques_num,ques_content)
--             values(2,'좋아하는 음악이 뭐야?');
-- insert into question(ques_num,ques_content)
--             values(3,'취미가 뭐야?');
-- insert into question(ques_num,ques_content)
--             values(4,'키가 몇이야?');
-- insert into question(ques_num,ques_content)
--             values(5,'몇 살이야?');
